language: node_js
node_js:
  - "0.10.33"
services:
  - postgresql
addons:
  postgresql: "9.3"
  sauce_connect: true
notifications:
  email: false
script:
  - npm run syntax
  - npm test
before_script:
  - psql -c 'create database accountability_test;' -U postgres
  - cd test/scripts; ./create_db.sh accountability_test; cd ../..;
  - PORT=9000 node server/index.js&
  - sleep 5
after_script:
  - npm run coveralls
  - npm run e2e
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/accountability_test
    - AWS_BUCKET=logan-accountability-test
    # AWS_SECRET_ACCESS_KEY
    - secure: "nFZBa6FGJTyFmvFpLClk8LsgsOn1WjkGSTWjNkj8VGUSLX2GEmUu6dyurk2L+XktcrLma+7Ooy2eDk24spvfZKp+ayTfLnr4bHVTbxCaHxiTVNyfaHQOm8xV/8ROBr5QRNP2wbrhRi9i8cgZHK+teonSHqHT+uSOTRnET1GGHEs="
    # AWS_ACCESS_KEY_ID
    - secure: "UwDQB4JXF/zp8iwacWppMhXYme27bsLuygVgRXOnKWotokzIr54Mnc2IvqDDvOUnYNKnBOhNaxDUyLs8ivSAyj4aorfgNTfHnu6mWEzWM/1ZV0ttRDdBqhUmZGsl02eSwjCc7VHKqpX9mbx9DFGHksw/jnS+/Muj80mru0bxL98="
    #SAUCE_USERNAME
    - secure: "GapAcHXUzDU/Ai3pIajGkD9yKsAAfY/fV6jJXw4y1qVNdzzRTqSV6XZAEzy8Qj++IslbEFK4OlNdNW8LRxcjTx/qX/fWkYqq+2iUiTL06tzt+r+N6rm4c2MUteB4T2BRYenfCv+BnBV6wMhxXXORFaY2f13MjXZV0HKCK7b4BeY="
    #SAUCE_ACCESS_KEY
    - secure: "SrHdICv3LOlckhOIETRLKCrzX6xGAwGgRIQrSRZ4OGKq1AbeOb3I4F/ptZ35kZQw75y2l65tOYXmT/wKfTxfonVzprZNiRI0UoPyFWbDHKwQXWX0mAfzbB3rD2ay9J9EpK3LuOaw0n+qwqEb6+7OkIr+Mp7IUE/o2lnIeWm2Ghg="
